# Generated by Django 5.0 on 2024-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default='', max_length=300)),
                ('client_secret', models.CharField(blank=True, default='', max_length=300)),
                ('scopes', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
