# Generated by Django 5.0.3 on 2024-03-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonimo', max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount_purpose', models.TextField(max_length=355)),
                ('work_information', models.TextField(max_length=300)),
                ('references_peopple', models.TextField(max_length=500)),
            ],
        ),
    ]
