# Generated by Django 5.0 on 2024-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='mora',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
