# Generated by Django 5.0.3 on 2024-03-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
