# Generated by Django 5.0 on 2024-11-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_cuota_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='dias_en_atraso',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
