# Generated by Django 5.0.3 on 2024-03-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_customer_img1_customer_img2_customer_no_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
