# Generated by Django 5.0.3 on 2024-03-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_customer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
