# Generated by Django 5.0 on 2024-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_credit_precio_a_saldar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amount_feed_int',
            field=models.CharField(default='0.00', max_length=100),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount_str',
            field=models.CharField(default='0.00', max_length=100),
        ),
    ]
