# Generated by Django 5.0 on 2024-12-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_credit_amount_feed_int_alter_credit_amount_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='group_letter',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
    ]
