# Generated by Django 5.0.3 on 2024-03-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_r1',
            field=models.CharField(default='Primera Referencia', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_r2',
            field=models.CharField(default='Segunda Referencia', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_r1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_r2',
            field=models.IntegerField(default=0),
        ),
    ]
