# Generated by Django 5.0 on 2024-12-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_abc_credit_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='category',
        ),
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
