# Generated by Django 5.0.3 on 2024-03-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_customer_name_r1_alter_customer_name_r2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number_r1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_r2',
            field=models.IntegerField(),
        ),
    ]
