# Generated by Django 5.0 on 2024-12-05 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_credit', to='Customer.category'),
        ),
    ]
