# Generated by Django 5.0.3 on 2024-03-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_alter_customer_number_r1_alter_customer_number_r2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.FloatField(),
        ),
    ]
