# Generated by Django 5.0.3 on 2024-03-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_alter_customer_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='number',
        ),
        migrations.AddField(
            model_name='credit',
            name='dni',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='credit',
            name='price_feed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='credit',
            name='no_account',
            field=models.TextField(),
        ),
    ]
