# Generated by Django 5.0.3 on 2024-03-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_credit_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
