# Generated by Django 5.0.3 on 2024-03-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_alter_credit_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='day_pay2',
        ),
    ]
