# Generated by Django 5.0.3 on 2024-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_remove_credit_day_pay2'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='amount_feed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
