# Generated by Django 5.0.3 on 2024-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_credit_amount_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lat',
            field=models.CharField(default='', max_length=1055),
        ),
        migrations.AddField(
            model_name='customer',
            name='lon',
            field=models.CharField(default='', max_length=1055),
        ),
    ]
