# Generated by Django 5.0.3 on 2024-03-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_customer_lat_customer_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.CharField(default='', max_length=100000000050005),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lon',
            field=models.CharField(default='', max_length=100000000000000055),
        ),
    ]
