# Generated by Django 5.0 on 2024-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0023_alter_customer_number_r1_alter_customer_number_r2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='calle_numero',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='calle_numero_trabajo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='cargo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='ciudad',
            field=models.CharField(default='Santo Domingo Este', max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='ciudad_trabaja',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='code_customer',
            field=models.CharField(default='', max_length=122000),
        ),
        migrations.AddField(
            model_name='customer',
            name='dir_referencia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='dir_referencia_trabajo',
            field=models.CharField(default='', max_length=244),
        ),
        migrations.AddField(
            model_name='customer',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='direccion_trabajo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='empresa_trabaja',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='estado_civil',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='moneda',
            field=models.CharField(default='RD$', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='municipio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='municipio_trabaja',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='nacimiento',
            field=models.CharField(default='10/11/2001', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='nacionalidad',
            field=models.CharField(default='DOMINICANA', max_length=25),
        ),
        migrations.AddField(
            model_name='customer',
            name='ocupacion',
            field=models.CharField(default='Estudiante', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='pais',
            field=models.CharField(default='REPUBLICA DOMINICANA', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='pais_trabajo',
            field=models.CharField(default='REPUBLICA DOMINICANA', max_length=244),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='provincia',
            field=models.CharField(default='SANTO DOMINGO DE GUZMAN', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='provincia_trabajo',
            field=models.CharField(default='SANTO DOMINGO DE GUZMAN', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='salario_m',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='sector',
            field=models.CharField(default='', max_length=244),
        ),
        migrations.AddField(
            model_name='customer',
            name='sexo',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='type_input',
            field=models.CharField(default='P', max_length=2),
        ),
    ]
