# Generated by Django 5.0 on 2024-04-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0024_customer_calle_numero_customer_calle_numero_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='atraso121_150',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='atraso151_180',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='atraso181_o_mas',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='atraso1_30',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='atraso31_60',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='atraso61_90',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='atraso91_120',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance_corte',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='cantidad_cuota',
            field=models.CharField(default='6', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='credito_aprovado',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='estatus',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='fecha_apertura',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='fecha_ultimo_pago',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='fecha_vencimiento',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='forma_pago',
            field=models.CharField(default='Mensual', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='moneda_prestamo',
            field=models.CharField(default='RD$', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='monto_adeudado',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='monto_ultimo_pago',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='numeoro_cuenta',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='pago_mandatorio_cuota',
            field=models.CharField(default='', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='relacion_tipo',
            field=models.CharField(default='1', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='tasa_interes',
            field=models.CharField(default='0.15', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='tipo_prestamo',
            field=models.CharField(default='N', max_length=233),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_atraso',
            field=models.CharField(default='', max_length=233),
        ),
    ]
