# Generated by Django 5.0 on 2024-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0025_customer_atraso121_150_customer_atraso151_180_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img1',
            field=models.ImageField(blank=True, default='media/img-default/img.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='img2',
            field=models.ImageField(blank=True, default='media/img-default/img.png', null=True, upload_to='media/'),
        ),
    ]
