# Generated by Django 5.0 on 2024-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0026_alter_customer_img1_alter_customer_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='moneda',
            field=models.CharField(default='RD$', max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ocupacion',
            field=models.CharField(default='Estudiante', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=18),
        ),
    ]
