# Generated by Django 5.0 on 2024-04-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0028_alter_customer_address_alter_customer_amount_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, default='Grupo Fycas', max_length=255),
        ),
    ]
