# Generated by Django 5.0 on 2024-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0032_alter_customer_address_alter_customer_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cargo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_r1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_r2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_r1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_r2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salario_m',
            field=models.CharField(default='', max_length=233),
        ),
    ]
