# Generated by Django 5.0 on 2024-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0033_alter_customer_cargo_alter_customer_name_r1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fines',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='monto_requerido',
            field=models.CharField(default='', max_length=255),
        ),
    ]
