# Generated by Django 5.0 on 2024-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0034_customer_fines_customer_monto_requerido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Grupo Fycas', max_length=233)),
                ('Icon', models.ImageField(blank=True, default='media/img-default/img.png', null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='aprobado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='casa',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='familiar_en_fycas',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fines',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fue_recomendado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monto_requerido',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tierra',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehiculo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
