# Generated by Django 5.0 on 2024-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0035_settingapp_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='amount_feed_int',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='credit',
            name='amount_str',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='credit',
            name='day',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='credit',
            name='day_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='credit',
            name='mont',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='credit',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='credit',
            name='year_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
