# Generated by Django 5.0 on 2024-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0036_credit_amount_feed_int_credit_amount_str_credit_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hijos',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='saldar_deudas',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
