# Generated by Django 5.0 on 2024-05-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0037_customer_hijos_customer_saldar_deudas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='media/')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.credit')),
            ],
        ),
    ]
