# Generated by Django 5.0 on 2024-05-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0038_paycredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ciudad',
            field=models.CharField(blank=True, default='Santo Domingo', max_length=250),
        ),
    ]
