# Generated by Django 5.0 on 2024-05-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0039_alter_customer_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='aprobado',
            new_name='not_aprobado',
        ),
    ]
