# Generated by Django 5.0 on 2024-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0040_rename_aprobado_customer_not_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_verify',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
