# Generated by Django 5.0 on 2024-05-21 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0042_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('dni', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('day_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='day_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='day_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
