# Generated by Django 5.0 on 2024-05-22 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0043_customerdebit_credit_day_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebit',
            name='day_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
