# Generated by Django 5.0 on 2024-05-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0044_alter_customerdebit_day_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debit',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
