# Generated by Django 5.0 on 2024-05-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0045_customer_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debit_follow',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
