# Generated by Django 5.0 on 2024-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0046_customer_debit_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debit_v',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
