# Generated by Django 5.0 on 2024-05-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0047_customer_debit_v'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='debit_v',
            new_name='debit_visit',
        ),
    ]
