# Generated by Django 5.0 on 2024-05-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0048_rename_debit_v_customer_debit_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_verify',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
