# Generated by Django 5.0 on 2024-09-27 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0049_alter_customer_customer_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='plazo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='credit',
            name='tasa',
            field=models.IntegerField(default=0.15),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.IntegerField(default=0)),
                ('capital', models.IntegerField(default=0)),
                ('capital_restante', models.IntegerField(default=0)),
                ('creado', models.DateField(default=django.utils.timezone.now)),
                ('pago', models.CharField(default='', max_length=20)),
                ('estado', models.BooleanField(default=False)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='Customer.credit')),
            ],
        ),
    ]
