# Generated by Django 5.0 on 2024-09-27 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0050_credit_plazo_credit_tasa_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='capital',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='capital_restante',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='creado',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='cuota',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='pago',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
