# Generated by Django 5.0 on 2024-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0051_alter_cuota_capital_alter_cuota_capital_restante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='tasa',
            field=models.IntegerField(default=15),
        ),
    ]
