# Generated by Django 5.0 on 2024-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0053_alter_credit_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
