# Generated by Django 5.0 on 2024-09-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0054_alter_credit_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=5),
        ),
    ]
