# Generated by Django 5.0 on 2024-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0055_alter_credit_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='tasa',
            field=models.IntegerField(default=15),
        ),
    ]
