# Generated by Django 5.0 on 2024-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0056_alter_credit_tasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='abonado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
