# Generated by Django 5.0 on 2024-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0057_cuota_abonado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='restante',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
