# Generated by Django 5.0 on 2024-10-26 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0060_cashcontrol_cuota_end_date_cuota_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
