# Generated by Django 5.0 on 2024-10-30 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0062_cuota_last_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='last_time_pay',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
