# Generated by Django 5.0 on 2024-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0063_cuota_last_time_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='estado_credito',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
