# Generated by Django 5.0 on 2024-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0064_credit_estado_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='credito_atraso_al_dia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
