# Generated by Django 5.0 on 2024-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0065_cuota_credito_atraso_al_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credito_atraso_al_dia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
