# Generated by Django 5.0 on 2024-11-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0066_credit_credito_atraso_al_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='credito_atraso_al_dia',
            new_name='credito_atrasado',
        ),
    ]
