# Generated by Django 5.0 on 2024-11-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0067_rename_credito_atraso_al_dia_cuota_credito_atrasado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='credito_atraso_al_dia',
            new_name='credito_atrasado',
        ),
    ]
