# Generated by Django 5.0 on 2024-11-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0068_rename_credito_atraso_al_dia_credit_credito_atrasado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='mora',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
