# Generated by Django 5.0 on 2024-11-16 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0069_cuota_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
    ]
