# Generated by Django 5.0 on 2024-11-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0071_remove_settingapp_customer_settingapp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='bg_enfasis',
            field=models.CharField(blank=True, default='rgb(83, 137, 255)', max_length=233),
        ),
    ]
