# Generated by Django 5.0 on 2024-11-17 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0073_modulo_company_optionmodulo_delete_settingapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='Customer.company'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
