# Generated by Django 5.0 on 2024-11-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0075_remove_modulo_icon_modulo_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='Icon',
            new_name='img',
        ),
        migrations.AddField(
            model_name='modulo',
            name='svg',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
