# Generated by Django 5.0 on 2024-11-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0077_alter_modulo_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='optionmodulo',
            name='name',
        ),
        migrations.AddField(
            model_name='optionmodulo',
            name='input_text',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='optionmodulo',
            name='is_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
