# Generated by Django 5.0 on 2024-11-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0079_remove_optionmodulo_modulo_configurationcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationcompany',
            name='name',
            field=models.CharField(default='Configuracion', max_length=100),
        ),
    ]
