# Generated by Django 5.0 on 2024-11-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0080_configurationcompany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionsconfiguration',
            name='name',
            field=models.CharField(default='Opcion', max_length=100),
        ),
    ]
