# Generated by Django 5.0 on 2024-11-17 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0084_alter_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_customer', to='Customer.company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, default='Grupo Fycas', max_length=255),
        ),
    ]
