# Generated by Django 5.0 on 2024-11-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0085_customer_company_customer_alter_customer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_customer',
        ),
    ]
