# Generated by Django 5.0 on 2024-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0089_company_created_at_company_rnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_provider',
            field=models.CharField(blank=True, choices=[('gmail', 'Gmail'), ('icloud', 'iCloud'), ('yahoo', 'Yahoo'), ('outlook', 'Outlook'), ('other', 'Other')], default='gmail', max_length=50, null=True),
        ),
    ]
