# Generated by Django 5.0 on 2024-11-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0090_company_email_company_email_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
