# Generated by Django 5.0 on 2024-11-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0092_alter_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='829-557-7196', max_length=233),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_provider',
            field=models.CharField(blank=True, choices=[('@gmail', 'Gmail'), ('@icloud', 'iCloud'), ('@yahoo', 'Yahoo'), ('@outlook', 'Outlook'), ('@other', 'Other')], default='gmail', max_length=50, null=True),
        ),
    ]
