# Generated by Django 5.0 on 2024-11-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0093_company_phone_alter_company_email_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_provider',
            field=models.CharField(blank=True, choices=[('@gmail.com', 'Gmail'), ('@icloud.com', 'iCloud'), ('@yahoo.com', 'Yahoo'), ('@outlook.com', 'Outlook'), ('@other', 'Other')], default='gmail', max_length=50, null=True),
        ),
    ]
