# Generated by Django 5.0 on 2024-11-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0094_alter_company_email_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='img2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
