# Generated by Django 5.0 on 2024-11-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0095_alter_customer_img1_alter_customer_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_credit', to='Customer.company'),
        ),
    ]
