# Generated by Django 5.0 on 2024-11-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0096_credit_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='Grupo Fycas', null=True),
        ),
    ]
