# Generated by Django 5.0 on 2024-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0097_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='key',
            field=models.TextField(blank=True),
        ),
    ]
