# Generated by Django 5.0 on 2024-11-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_company_icon_img_company_contrato_company_notarial'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='img',
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/item/'),
        ),
        migrations.CreateModel(
            name='Categori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Categoria 1', max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/categori/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categori_company', to='Customer.company')),
            ],
        ),
    ]
